development:
  clients:
    default:
      database: popolo_development
      hosts:
        - localhost:27017
test:
  clients:
    default:
      database: popolo_test
      hosts:
        - localhost:27017
